# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' ADMM algorithm for estimating sparse precision matrix based on prior knowledge
#' @name ADMM
#' @param Sigma Covariance matrix.
#' @param gammav Regularization term.
#' @param rho Penalty parameter of the augmented Lagrangian function.
#' @param max_iter Maximum number of the iterations.
#' @param numvariable Number of the variables (e.g., Transcription factors)
#'
#' @return A Sparse precision matrix
#' @export
NULL

ADMM <- function(Sigma, gammav, rho, max_iter, tol, numvariable) {
    .Call(`_DKGN_ADMM`, Sigma, gammav, rho, max_iter, tol, numvariable)
}

#' Function for data standardization
#' @name center
#' @param raw_data A n*p matrix.
#' @param standard A Boolean parameter that determines whether standardization is done.
#'
#' @return A Normal data
#' @export
NULL

center <- function(raw_data, standard = FALSE) {
    .Call(`_DKGN_center`, raw_data, standard)
}

#' Shrinkage estimator based on empirical Bayesian Approach
#' @name getIntensity
#' @param S  Sample covariance matrix.
#' @param target Target matrix.
#' @param lambda A sequence of lambda for shrinkage
#' @param n Number of the samples
#'
#' @return Shrinkage intensity
#' @export
NULL

getIntensity <- function(S, target, lambda, n) {
    .Call(`_DKGN_getIntensity`, S, target, lambda, n)
}

#' Get gartial correlation coefiicients from given precision matrix
#' @name PCorr
#' @param precision Precision matrix.
#'
#' @return A partial correlation matrix
#' @export
NULL

pCorr <- function(precision) {
    .Call(`_DKGN_pCorr`, precision)
}

